ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_confirm_token VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_confirm_expires_at TIMESTAMP NULL;
