-- Role table: GUEST, ADMIN, AUTHOR
CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO role (name) VALUES ('GUEST'), ('ADMIN'), ('AUTHOR')
ON CONFLICT (name) DO NOTHING;

-- Join table users <-> role
CREATE TABLE IF NOT EXISTS user_role (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES role(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- -- Migrate existing admin flag: give ADMIN role to users where admin = true
-- INSERT INTO user_role (user_id, role_id)
-- SELECT u.id, r.id FROM users u
-- CROSS JOIN role r
-- WHERE u.admin = TRUE AND r.name = 'ADMIN'
-- ON CONFLICT (user_id, role_id) DO NOTHING;
--
-- -- Give GUEST role to every user
-- INSERT INTO user_role (user_id, role_id)
-- SELECT u.id, r.id FROM users u
-- CROSS JOIN role r
-- WHERE r.name = 'GUEST'
-- ON CONFLICT (user_id, role_id) DO NOTHING;
--
-- -- Drop old admin column
-- ALTER TABLE users DROP COLUMN IF EXISTS admin;
